import { createHash, createPublicKey } from "node:crypto";
import { lstat, mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathExists, readJson } from "./configuration.mjs";

const ID=/^[a-z][a-z0-9-]*$/;
export class TrustError extends Error { constructor(message,code="TRUST_INVALID",exitCode=1,data){super(message);this.code=code;this.exitCode=exitCode;this.data=data;} }
function storePath(projectRoot){return path.join(path.resolve(projectRoot),".basic-structure","trust","publishers.json");}
export function publicKeyFingerprint(publicKey){const key=createPublicKey(publicKey);if(key.asymmetricKeyType!=="ed25519")throw new TrustError("Public key must be Ed25519.");return createHash("sha256").update(key.export({type:"spki",format:"der"})).digest("hex");}
export async function readTrustStore(projectRoot){const file=storePath(projectRoot);if(!(await pathExists(file)))return{schemaVersion:1,keys:[]};const info=await lstat(file);if(info.isSymbolicLink()||!info.isFile())throw new TrustError("Trust store must be a regular file.");const store=await readJson(file);if(store.schemaVersion!==1||!Array.isArray(store.keys))throw new TrustError("Invalid trust store.");return store;}
async function writeStore(projectRoot,store){const file=storePath(projectRoot);await mkdir(path.dirname(file),{recursive:true});const temporary=`${file}.tmp-${process.pid}`;await writeFile(temporary,`${JSON.stringify(store,null,2)}\n`,"utf8");await rename(temporary,file);}
export async function inspectPublisherKey(keyFile){const key=await readJson(path.resolve(keyFile));if(key.schemaVersion!==1||key.algorithm!=="ed25519"||!ID.test(key.publisher??"")||!ID.test(key.keyId??""))throw new TrustError("Invalid publisher key metadata.");const fingerprint=publicKeyFingerprint(key.publicKey);if(key.fingerprint!==`sha256:${fingerprint}`)throw new TrustError("Publisher key fingerprint mismatch.","TRUST_FINGERPRINT_MISMATCH");return{...key,fingerprint:key.fingerprint};}
export async function addTrustedKey(projectRoot,keyFile,apply){const key=await inspectPublisherKey(keyFile);const store=await readTrustStore(projectRoot);if(store.keys.some((entry)=>entry.publisher===key.publisher&&entry.keyId===key.keyId))throw new TrustError("Publisher key already exists.","TRUST_KEY_EXISTS");const entry={publisher:key.publisher,keyId:key.keyId,algorithm:"ed25519",publicKey:key.publicKey,fingerprint:key.fingerprint,status:"trusted",addedAt:new Date().toISOString()};if(apply){store.keys.push(entry);store.keys.sort((a,b)=>`${a.publisher}/${a.keyId}`.localeCompare(`${b.publisher}/${b.keyId}`));await writeStore(projectRoot,store);}return{entry,applied:Boolean(apply)};}
export async function revokeTrustedKey(projectRoot,publisher,keyId,apply){if(!ID.test(publisher??"")||!ID.test(keyId??""))throw new TrustError("Publisher and key id must be valid.");const store=await readTrustStore(projectRoot);const entry=store.keys.find((item)=>item.publisher===publisher&&item.keyId===keyId);if(!entry)throw new TrustError("Trusted key was not found.","TRUST_KEY_NOT_FOUND");if(entry.status==="revoked")throw new TrustError("Trusted key is already revoked.","TRUST_KEY_REVOKED");if(apply){entry.status="revoked";entry.revokedAt=new Date().toISOString();await writeStore(projectRoot,store);}return{entry:{...entry,...(apply?{}:{status:"revoked"})},applied:Boolean(apply)};}
